Repository QuiltMC/quilt-kotlin-libraries, pull requests merged in 2022-11, with the labels that each got.

#52 Add package documentation for Brigadier and make use of Text DSL in samples
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/brigadier/brigadier.md
  wrapper/minecraft/src/main/kotlin/samples/qkl/brigadier/BrigadierDslSamples.kt
Labels: documentation, fast track

#49 kotlinx.serialization to mojang serialization bridge
  build.gradle.kts
  gradle/libs.versions.toml
  wrapper/minecraft/src/main/java/org/quiltmc/qkl/wrapper/minecraft/mixin/serialization/ForwardingDynamicOpsAccessor.java
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/CodecFactory.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/ExtendedDynamicOps.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/annotation/CodecEntryListMap.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/annotation/CodecSerializable.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/CodecSerializationException.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/CodecSerializerAdapter.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/DefaultExtendedOps.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/ExtendedJsonOps.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/SerializationState.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/SerializerCodec.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/decoder/BasicStates.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/decoder/ClassStates.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/decoder/CollectionStates.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/decoder/DecoderState.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/decoder/DynamicDecoder.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/encoder/BasicStates.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/encoder/ClassStates.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/encoder/CollectionStates.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/encoder/DynamicEncoder.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/encoder/EncoderState.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/util/AnnotationUtil.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/util/DataUtil.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/util/ValidationUtil.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/options/CodecOptions.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/options/CodecOptionsBuilder.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/serialization.md
  wrapper/minecraft/src/main/kotlin/samples/qkl/serialization/BasicSerializationTests.kt
  wrapper/minecraft/src/main/kotlin/samples/qkl/serialization/MapSerializationTests.kt
  wrapper/minecraft/src/main/kotlin/samples/qkl/serialization/NullableSerializationTests.kt
  wrapper/minecraft/src/main/kotlin/samples/qkl/serialization/PolymorphicSerializationTests.kt
  wrapper/minecraft/src/main/kotlin/samples/qkl/serialization/SerializationTestUtils.kt
  wrapper/minecraft/src/main/resources/qkl_minecraft.mixins.json
Labels: final comment

#20 Improve repository appearence
  .github/ISSUE_TEMPLATES/bug_report.yml
  .github/ISSUE_TEMPLATES/config.yml
  .github/ISSUE_TEMPLATES/feature_request.yml
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement, draft, fast track

#48 Add binary compatibility validator
  api/quilt-kotlin-libraries.api
  build.gradle.kts
  gradle/libs.versions.toml
  wrapper/api/wrapper.api
  wrapper/minecraft/api/minecraft.api
  wrapper/qsl/api/qsl.api
Labels: enhancement, final comment, fast track
