Repository QuiltMC/quilt-kotlin-libraries, pull requests merged in 2022-06, with the labels that each got.

#10 Clean up Kotlin adapter and make it more readable
  core/src/main/kotlin/org/quiltmc/qkl/core/adapter/KotlinAdapter.kt
Labels: enhancement, fast track

#12 Implement fatjar as a submodule
  build.gradle.kts
  fatjar/build.gradle.kts
  fatjar/src/main/resources/quilt.mod.json
  settings.gradle.kts
Labels: enhancement

#17 Add some Detekt checks
  codeformat/detekt.yml
  core/src/main/kotlin/org/quiltmc/qkl/core/adapter/KotlinAdapter.kt
Labels: enhancement, fast track

#7 Add Registry DSL
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/registry/RegistryDsl.kt
Labels: enhancement, final comment

#22 Math operators (attempt 2)
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/math/InternalUtil.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/math/Vec2fOps.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/math/Vec3dOps.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/math/Vec3fOps.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/math/Vec3iOps.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/math/Vector2fOps.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/math/Vector3dOps.kt
  wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/math/Vector4fOps.kt
Labels: final comment
